{
 "title": "DevOps API Monitoring",
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 6 },
   "targets": [
    { "expr": "app_requests_total" }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 6 },
   "targets": [
    { "expr": "rate(app_requests_total[1m])" }
   ]
  },
  {
   "title": "Service Status",
   "type": "stat",
   "gridPos": { "x": 0, "y": 6, "w": 12, "h": 6 },
   "targets": [
    { "expr": "up" }
   ]
  }
 ]
}